package com.grayunited.payments.model;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.OffsetDateTime;

@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
@EqualsAndHashCode(onlyExplicitlyIncluded = true)
@Entity
@Table(name = "enrollments")
public class Enrollment {

    // FIXED: Removed @GeneratedValue.
    // The Vault must explicitly accept and persist the exact UUID generated by Python.
    @Id
    @EqualsAndHashCode.Include
    @Column(name = "id", length = 36, nullable = false, updatable = false)
    private String id;

    @Column(name = "user_id", length = 36, nullable = false)
    private String userId;

    @Column(name = "course_id", nullable = false)
    private String courseId;

    @Column(name = "course_title")
    private String courseTitle;

    @Column(name = "status", length = 20, nullable = false)
    private String status; // 'pending', 'completed', 'failed'

    @Column(name = "razorpay_order_id", unique = true, length = 255)
    private String razorpayOrderId;

    // FIXED: Upgraded to OffsetDateTime to ensure perfect timezone alignment
    // with Python's DateTime(timezone=True) in PostgreSQL.
    @CreationTimestamp
    @Column(name = "created_at", updatable = false)
    private OffsetDateTime createdAt;

    @UpdateTimestamp
    @Column(name = "updated_at")
    private OffsetDateTime updatedAt;
}